# Generated by Django 5.1.6 on 2025-03-16 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 20, 31, 31, 41753, tzinfo=datetime.timezone.utc)),
        ),
    ]
