# Generated by Django 5.1.6 on 2025-03-16 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0002_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(default=0)),
                ('literacy_rate', models.FloatField(default=0.0)),
                ('ongoing_projects', models.IntegerField(default=0)),
                ('annual_budget', models.CharField(default='Not specified', max_length=255)),
                ('village_location', models.CharField(default='Not specified', max_length=255)),
                ('employment_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 21, 1, 52, 169886, tzinfo=datetime.timezone.utc)),
        ),
    ]
