# Generated by Django 5.1.6 on 2025-03-16 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0005_villageupdate_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 21, 21, 22, 735207, tzinfo=datetime.timezone.utc)),
        ),
    ]
