# Generated by Django 5.1.6 on 2025-03-16 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0006_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanchayatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image_url', models.URLField(default='https://via.placeholder.com/100')),
            ],
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 21, 34, 47, 799840, tzinfo=datetime.timezone.utc)),
        ),
    ]
