# Generated by Django 5.1.6 on 2025-03-16 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0008_meeting_created_by_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-views'],
            },
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 22, 33, 8, 845194, tzinfo=datetime.timezone.utc)),
        ),
    ]
