# Generated by Django 5.1.6 on 2025-03-16 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0009_faq_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event or image', max_length=255)),
                ('image', models.ImageField(help_text='Upload an image for the gallery', upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 22, 47, 55, 674127, tzinfo=datetime.timezone.utc)),
        ),
    ]
