# Generated by Django 5.1.6 on 2025-03-20 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0010_galleryimage_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 20, 22, 5, 25, 835612, tzinfo=datetime.timezone.utc)),
        ),
    ]
