# Generated by Django 5.1.6 on 2025-04-02 11:24

import datetime
import gramapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0014_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='dob',
            field=models.DateField(validators=[gramapp.models.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='birthcertificate',
            name='document',
            field=models.FileField(upload_to=gramapp.models.birth_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='deathcertificate',
            name='date_of_death',
            field=models.DateField(validators=[gramapp.models.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='deathcertificate',
            name='document',
            field=models.FileField(upload_to=gramapp.models.death_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='domicilecertificate',
            name='document',
            field=models.FileField(upload_to=gramapp.models.domicile_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='marriagecertificate',
            name='date_of_marriage',
            field=models.DateField(validators=[gramapp.models.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='marriagecertificate',
            name='document',
            field=models.FileField(upload_to=gramapp.models.marriage_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 2, 11, 24, 41, 704169, tzinfo=datetime.timezone.utc)),
        ),
    ]
