# Generated by Django 5.1.6 on 2025-04-02 11:51

import datetime
import gramapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0015_alter_birthcertificate_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=gramapp.models.birth_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 2, 11, 51, 36, 901850, tzinfo=datetime.timezone.utc)),
        ),
    ]
