# Generated by Django 5.1.6 on 2025-04-02 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0016_alter_birthcertificate_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 2, 12, 8, 44, 327512, tzinfo=datetime.timezone.utc)),
        ),
    ]
