# Generated by Django 5.1.6 on 2025-04-03 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0019_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 3, 6, 10, 0, 1959, tzinfo=datetime.timezone.utc)),
        ),
    ]
