# Generated by Django 5.1.6 on 2025-04-03 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0022_remove_surveyresponse_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 3, 6, 57, 59, 219255, tzinfo=datetime.timezone.utc)),
        ),
    ]
