# Generated by Django 5.1.6 on 2025-04-03 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0023_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='Comma-separated choices for MCQ'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('mcq', 'Multiple Choice'), ('yes_no', 'Yes/No'), ('number', 'Numeric')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 3, 7, 15, 46, 509406, tzinfo=datetime.timezone.utc)),
        ),
    ]
