# Generated by Django 5.1.6 on 2025-04-03 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0025_remove_event_image_event_image_base64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 3, 9, 0, 51, 656278, tzinfo=datetime.timezone.utc)),
        ),
    ]
