# Generated by Django 5.1.6 on 2025-04-03 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0026_remove_event_image_base64_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 3, 9, 5, 37, 625917, tzinfo=datetime.timezone.utc)),
        ),
    ]
