# Generated by Django 5.1.6 on 2025-04-05 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0027_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchayatmember',
            name='image_url',
        ),
        migrations.AddField(
            model_name='panchayatmember',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 5, 10, 30, 39, 719227, tzinfo=datetime.timezone.utc)),
        ),
    ]
