# Generated by Django 5.1.6 on 2025-04-05 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0028_remove_panchayatmember_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 5, 11, 35, 32, 644596, tzinfo=datetime.timezone.utc)),
        ),
    ]
