# Generated by Django 5.1.6 on 2025-04-05 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0029_alter_question_options_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 5, 12, 15, 14, 787479, tzinfo=datetime.timezone.utc)),
        ),
    ]
