# Generated by Django 5.1.6 on 2025-04-05 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0030_alter_taxpayment_valid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShramdanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_base64', models.TextField(help_text='Base64-encoded image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 5, 12, 42, 24, 44226, tzinfo=datetime.timezone.utc)),
        ),
    ]
